"""
design_social_post.py — Auto-generate branded Instagram graphics from a
base photo + hook text. Outputs both Feed (4:5, 1080×1350) and Story
(9:16, 1080×1920) variants.

WHY THIS EXISTS (14 Jun 2026)
    Tia: "I want auto generated by AI" — for a trend-ride post, Joanne
    shouldn't have to open Canva and recreate the brand layout every
    time. This script takes the asset metadata + caption and emits two
    ready-to-post JPGs with the CB247 brand applied.

BRAND RULES (from context/design-standards.md)
    - Colours: teal #3FA69A, black #1a1a1a, white #ffffff, gray scale.
      No other colours.
    - No emojis in UI overlays. Copy-only emojis are fine in body
      captions (NOT applied here — this is the visual graphic).
    - CB247 logo bottom-right corner.

CLI
    python scripts/design_social_post.py \
        --asset docs/Image/Ellenbrook/P1071860.JPG \
        --hook "3 MIN IN THE ICE BATH" \
        --subhook "> 30 min scrolling" \
        --slug coldplunge-2026-06-14 \
        --price "$11.95/week · no lock-in"

OUTPUT
    docs/Image/social-posts/{slug}-feed.jpg   (1080×1350, 4:5)
    docs/Image/social-posts/{slug}-story.jpg  (1080×1920, 9:16)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

BASE_DIR = Path(__file__).resolve().parent.parent
LOGO_PATH = BASE_DIR / "Image" / "ChasingBetterGym_small_logo.jpeg"
OUT_DIR = BASE_DIR / "docs" / "Image" / "social-posts"

# Brand palette
TEAL = (63, 166, 154)
TEAL_DEEP = (45, 125, 114)
BLACK = (26, 26, 26)
WHITE = (255, 255, 255)
SHADOW = (0, 0, 0, 180)

# macOS system fonts that ship out of the box
FONT_HEAVY = "/System/Library/Fonts/Supplemental/Impact.ttf"
FONT_BOLD = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
FONT_REGULAR = "/System/Library/Fonts/Supplemental/Arial.ttf"


def _load_font(path: str, size: int) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(path, size)
    except OSError:
        return ImageFont.load_default()


def _crop_cover(img: Image.Image, target_w: int, target_h: int) -> Image.Image:
    """Crop + scale `img` to exactly cover target_w × target_h, centred."""
    src_w, src_h = img.size
    src_ratio = src_w / src_h
    tgt_ratio = target_w / target_h
    if src_ratio > tgt_ratio:
        # source is wider — scale to height, crop sides
        new_h = target_h
        new_w = round(src_w * (target_h / src_h))
    else:
        new_w = target_w
        new_h = round(src_h * (target_w / src_w))
    img = img.resize((new_w, new_h), Image.LANCZOS)
    left = (new_w - target_w) // 2
    top = (new_h - target_h) // 2
    return img.crop((left, top, left + target_w, top + target_h))


def _gradient_overlay(width: int, height: int, fade_height: int, top: bool = True) -> Image.Image:
    """Black-to-transparent gradient for text readability."""
    overlay = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    for y in range(fade_height):
        alpha = round(180 * (1 - y / fade_height)) if top else round(180 * (y / fade_height))
        row_y = y if top else height - fade_height + y
        draw.rectangle([(0, row_y), (width, row_y + 1)], fill=(0, 0, 0, alpha))
    return overlay


def _draw_text_with_shadow(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    text: str,
    font: ImageFont.FreeTypeFont,
    fill=WHITE,
    shadow_offset: int = 3,
) -> None:
    """Draw text with a soft shadow so it reads against busy backgrounds."""
    x, y = xy
    draw.text((x + shadow_offset, y + shadow_offset), text, font=font, fill=(0, 0, 0, 220))
    draw.text(xy, text, font=font, fill=fill)


def _paste_logo(canvas: Image.Image, position: str = "br", margin: int = 36, max_w: int = 140) -> None:
    """Paste the CB247 logo. position: 'br' (bottom-right) or 'tr' (top-right)."""
    if not LOGO_PATH.exists():
        return
    logo = Image.open(LOGO_PATH).convert("RGBA")
    ratio = max_w / logo.width
    logo = logo.resize((max_w, round(logo.height * ratio)), Image.LANCZOS)
    if position == "br":
        x = canvas.width - logo.width - margin
        y = canvas.height - logo.height - margin
    else:
        x = canvas.width - logo.width - margin
        y = margin
    canvas.paste(logo, (x, y), logo)


def _wrap_text(text: str, font: ImageFont.FreeTypeFont, max_width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        trial = (" ".join(current + [word])).strip()
        bbox = font.getbbox(trial)
        if bbox[2] - bbox[0] <= max_width:
            current.append(word)
        else:
            if current:
                lines.append(" ".join(current))
            current = [word]
    if current:
        lines.append(" ".join(current))
    return lines


def _render_feed(
    asset_img: Image.Image,
    hook: str,
    subhook: str,
    price: str,
    handle: str,
) -> Image.Image:
    W, H = 1080, 1350  # IG feed 4:5
    photo = _crop_cover(asset_img.copy(), W, H - 180)  # leave 180px teal band

    canvas = Image.new("RGB", (W, H), TEAL)
    canvas.paste(photo, (0, 0))

    # Top gradient for hook readability
    canvas_rgba = canvas.convert("RGBA")
    top_grad = _gradient_overlay(W, H - 180, 380, top=True)
    canvas_rgba.alpha_composite(top_grad, (0, 0))

    draw = ImageDraw.Draw(canvas_rgba)

    # Hook (large Impact, white, top area)
    hook_font = _load_font(FONT_HEAVY, 96)
    lines = _wrap_text(hook.upper(), hook_font, W - 120)
    y_cursor = 60
    for line in lines:
        bbox = hook_font.getbbox(line)
        x = (W - (bbox[2] - bbox[0])) // 2
        _draw_text_with_shadow(draw, (x, y_cursor), line, hook_font, fill=WHITE, shadow_offset=4)
        y_cursor += (bbox[3] - bbox[1]) + 16

    # Subhook (smaller, italic-ish bold)
    if subhook:
        sub_font = _load_font(FONT_BOLD, 44)
        bbox = sub_font.getbbox(subhook)
        x = (W - (bbox[2] - bbox[0])) // 2
        _draw_text_with_shadow(draw, (x, y_cursor + 16), subhook, sub_font, fill=WHITE, shadow_offset=2)

    # Teal bottom band
    band_y = H - 180
    draw.rectangle([(0, band_y), (W, H)], fill=TEAL)

    # Band text: left side = price, right side = handle
    price_font = _load_font(FONT_HEAVY, 56)
    handle_font = _load_font(FONT_BOLD, 28)

    price_bbox = price_font.getbbox(price)
    draw.text((48, band_y + 56), price, font=price_font, fill=WHITE)

    if handle:
        hbox = handle_font.getbbox(handle)
        draw.text((48, band_y + 124), handle, font=handle_font, fill=(255, 255, 255, 220))

    final = canvas_rgba.convert("RGB")
    _paste_logo(final, position="br", margin=36, max_w=140)
    return final


def _render_story(
    asset_img: Image.Image,
    hook: str,
    subhook: str,
    price: str,
    handle: str,
) -> Image.Image:
    W, H = 1080, 1920  # IG story 9:16
    photo_h = round(H * 0.62)
    photo = _crop_cover(asset_img.copy(), W, photo_h)

    canvas = Image.new("RGB", (W, H), TEAL)
    canvas.paste(photo, (0, 0))

    canvas_rgba = canvas.convert("RGBA")
    # Gradient at bottom of photo so headline reads off the band edge
    bot_grad = _gradient_overlay(W, photo_h, 260, top=False)
    canvas_rgba.alpha_composite(bot_grad, (0, 0))

    draw = ImageDraw.Draw(canvas_rgba)

    # Bottom teal band already filled by base. Add hook at top of band.
    band_top = photo_h + 40
    hook_font = _load_font(FONT_HEAVY, 96)
    lines = _wrap_text(hook.upper(), hook_font, W - 120)
    y_cursor = band_top
    for line in lines:
        bbox = hook_font.getbbox(line)
        x = (W - (bbox[2] - bbox[0])) // 2
        draw.text((x, y_cursor), line, font=hook_font, fill=WHITE)
        y_cursor += (bbox[3] - bbox[1]) + 12

    if subhook:
        sub_font = _load_font(FONT_BOLD, 48)
        bbox = sub_font.getbbox(subhook)
        x = (W - (bbox[2] - bbox[0])) // 2
        draw.text((x, y_cursor + 28), subhook, font=sub_font, fill=WHITE)
        y_cursor += (bbox[3] - bbox[1]) + 28

    # Price + handle near bottom
    price_font = _load_font(FONT_HEAVY, 64)
    handle_font = _load_font(FONT_BOLD, 32)

    bbox = price_font.getbbox(price)
    draw.text(((W - (bbox[2] - bbox[0])) // 2, H - 260), price, font=price_font, fill=WHITE)

    if handle:
        hbox = handle_font.getbbox(handle)
        draw.text(((W - (hbox[2] - hbox[0])) // 2, H - 170), handle, font=handle_font, fill=(255, 255, 255, 220))

    final = canvas_rgba.convert("RGB")
    _paste_logo(final, position="tr", margin=36, max_w=120)
    return final


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--asset", required=True, help="Source photo path (relative to repo root)")
    p.add_argument("--hook", required=True, help="Top headline, e.g. '3 MIN IN THE ICE BATH'")
    p.add_argument("--subhook", default="", help="Secondary line under the hook")
    p.add_argument("--price", default="$11.95/week · no lock-in", help="Bottom price line")
    p.add_argument("--handle", default="@chasingbetter247", help="Bottom handle line")
    p.add_argument("--slug", required=True, help="Output filename slug (no extension)")
    args = p.parse_args()

    src = BASE_DIR / args.asset
    if not src.exists():
        print(f"ERROR: asset not found: {src}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    asset = Image.open(src).convert("RGB")

    feed = _render_feed(asset, args.hook, args.subhook, args.price, args.handle)
    feed_path = OUT_DIR / f"{args.slug}-feed.jpg"
    feed.save(feed_path, "JPEG", quality=88, optimize=True)
    print(f"  → wrote {feed_path.relative_to(BASE_DIR)} ({feed_path.stat().st_size // 1024} KB)")

    story = _render_story(asset, args.hook, args.subhook, args.price, args.handle)
    story_path = OUT_DIR / f"{args.slug}-story.jpg"
    story.save(story_path, "JPEG", quality=88, optimize=True)
    print(f"  → wrote {story_path.relative_to(BASE_DIR)} ({story_path.stat().st_size // 1024} KB)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
