"""
inject_seo_refresh_list.py — embed the list of available SEO refresh drafts
into docs/index.html so the View Brief renderer only shows the "View AI Draft"
button when the draft actually exists.

INPUT
    outputs/seo-refreshes/*.md  (one file per drafted SEO refresh action)

OUTPUT
    docs/index.html — injects a <script id="seo-refresh-list-block"> tag
    that sets window.AI_SEO_REFRESHES = ["slug1", "slug2", ...]

WHY
    Before this: brief renderer optimistically showed "View AI Draft →" for
    every SEO-organic action, and the link 404'd if no draft existed.
    After: button is hidden unless the slug is in window.AI_SEO_REFRESHES.

WHEN IT RUNS
    Wired into phase1c_content_drafter.sh — runs after render_content_html.py
    so the embedded list always reflects what's actually been drafted.
"""

import json
import re
from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
DRAFTS_DIR  = BASE_DIR / "outputs" / "seo-refreshes"
INDEX_PATH  = BASE_DIR / "docs" / "index.html"


def build_payload() -> list[str]:
    """List slugs of available SEO refresh drafts (stems of .md files)."""
    if not DRAFTS_DIR.exists():
        return []
    return sorted(p.stem for p in DRAFTS_DIR.glob("*.md") if p.is_file())


def inject() -> None:
    slugs = build_payload()
    payload_json = json.dumps(slugs)

    html = INDEX_PATH.read_text(encoding="utf-8")
    new_block = (
        '<script id="seo-refresh-list-block">\n'
        '// CB247 available SEO refresh drafts — auto-generated by\n'
        '// scripts/inject_seo_refresh_list.py (runs from phase1c).\n'
        '// Brief renderer checks this list before showing "View AI Draft".\n'
        f'window.AI_SEO_REFRESHES = {payload_json};\n'
        '</script>'
    )

    if 'id="seo-refresh-list-block"' in html:
        updated = re.sub(
            r'<script id="seo-refresh-list-block">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # 13 Jun 2026 — Tia bug fix: the brief renderer JS includes a
        # template literal containing the literal string `</body>` (the
        # brief opens as a full HTML doc in a blob:// tab). Using
        # str.replace("</body>", ...) hits the FIRST occurrence, which is
        # INSIDE that template literal — corrupting the whole dashboard JS.
        # Use rfind() to splice at the file's ACTUAL closing </body>.
        idx = html.rfind("</body>")
        if idx >= 0:
            updated = html[:idx] + new_block + "\n" + html[idx:]
            action = "inserted (at rightmost </body>)"
        else:
            updated = html + "\n" + new_block
            action = "appended"

    if updated == html:
        print("[seo-refresh-list] WARN — no change to docs/index.html")
        return

    INDEX_PATH.write_text(updated, encoding="utf-8")
    print(f"[seo-refresh-list] OK — {action} list of {len(slugs)} draft(s)")


if __name__ == "__main__":
    inject()
