"""
inject-meta-ads.py — Inject the latest Meta ads block into docs/index.html.

Same inline-injection pattern as inject-seo-extras.py and inject-social-block.py.
Reads state/ads-data.json meta_ads (newest week first) and writes:
  <script id="meta-ads-block">window.META_ADS_LIVE = {...}</script>

The frontend renderMeta uses window.META_ADS_LIVE.top_ads (when present)
in preference to the stale window.DASHBOARD_DATA.meta.top_ads. This
recovers per-ad account_id / account_name / location after pull_meta.py
adds those fields without needing to run the destructive baker.

Run after pull_meta.py:
  ./.venv/bin/python3.13 scripts/pull_meta.py
  ./.venv/bin/python3.13 scripts/inject-meta-ads.py
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
STATE_DIR = BASE_DIR / "state"
INDEX_PATH = BASE_DIR / "docs" / "index.html"
ADS_DATA_FILE = STATE_DIR / "ads-data.json"


def build_payload():
    if not ADS_DATA_FILE.exists():
        return None
    try:
        ads_data = json.loads(ADS_DATA_FILE.read_text())
    except Exception as e:
        print(f"[meta-ads] could not parse {ADS_DATA_FILE}: {e}")
        return None

    meta_weeks = ads_data.get("meta_ads") or []
    if not meta_weeks:
        return None

    latest = meta_weeks[0]
    history = meta_weeks[:4]  # 4 weeks for the trend chart

    return {
        "generated_at":  datetime.now(timezone.utc).isoformat(),
        "week_label":    latest.get("week_label", ""),
        "start":         latest.get("start", ""),
        "end":           latest.get("end", ""),
        "combined":      latest.get("combined") or {},
        "malaga_paid":   latest.get("malaga") or {},
        "ell_paid":      latest.get("ellenbrook") or {},
        "top_ads":       latest.get("ads") or [],
        "history": [
            {
                "week_label": w.get("week_label", ""),
                "combined":   w.get("combined") or {},
                "malaga":     w.get("malaga") or {},
                "ellenbrook": w.get("ellenbrook") or {},
                "ads":        w.get("ads") or [],
            }
            for w in history
        ],
    }


def inject():
    payload = build_payload()
    if payload is None:
        print("[meta-ads] No Meta ads data to inject — run pull_meta.py first.")
        return

    json_payload = json.dumps(payload, indent=2, default=str)
    html = INDEX_PATH.read_text(encoding="utf-8")

    new_block = (
        '<script id="meta-ads-block">\n'
        '// CB247 Meta ads — live override for window.DASHBOARD_DATA.meta\n'
        '// Auto-generated by scripts/inject-meta-ads.py from state/ads-data.json\n'
        f'window.META_ADS_LIVE = {json_payload};\n'
        '</script>'
    )

    if 'id="meta-ads-block"' in html:
        updated = re.sub(
            r'<script id="meta-ads-block">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # Insert just before window.DASHBOARD_DATA, like sibling injectors
        anchor = 'window.DASHBOARD_DATA = {'
        idx = html.find(anchor)
        if idx == -1:
            updated = html.replace("</body>", new_block + "\n</body>")
        else:
            script_open = html.rfind("<script>", 0, idx)
            if script_open == -1:
                updated = html.replace("</body>", new_block + "\n</body>")
            else:
                updated = html[:script_open] + new_block + "\n" + html[script_open:]
        action = "inserted"

    if updated == html:
        print("[meta-ads] WARN — no change to index.html")
        return

    INDEX_PATH.write_text(updated, encoding="utf-8")
    n_ads = len(payload.get("top_ads") or [])
    n_history = len(payload.get("history") or [])
    print(f"[meta-ads] OK — block {action} in docs/index.html")
    print(f"           Week:    {payload.get('week_label','?')}")
    print(f"           Top ads: {n_ads}")
    print(f"           History: {n_history} weeks")
    # Sanity check: how many ads have account info populated
    with_acct = sum(1 for a in (payload.get("top_ads") or []) if a.get("account_id"))
    print(f"           Ads with account_id: {with_acct}/{n_ads}"
          f"{' (run pull_meta.py to populate)' if with_acct < n_ads else ''}")


if __name__ == "__main__":
    inject()
