"""
inject_paid_ad_lists.py — embed lists of available Meta + Google Ads drafts
into docs/index.html so the View Brief renderer only shows the "View AI
Draft" button when the draft actually exists.

INPUT
    outputs/meta-ads/*.md          (Meta ad drafts)
    outputs/google-ads-rsa/*.md    (Google Ads RSA drafts)

OUTPUT
    docs/index.html — injects a <script id="paid-ad-list-block"> tag that
    sets:
        window.AI_META_ADS    = [slug1, slug2, ...]
        window.AI_GOOGLE_RSAS = [slug1, slug2, ...]

WHY THE rfind() PATTERN
    docs/index.html contains a JS template literal inside
    _renderProposedActionBriefHTML(row) that includes the literal string
    </body> (because the brief is a full HTML doc rendered into a blob://
    tab). A naive str.replace('</body>', ...) would corrupt that template
    literal — and DID, on 2026-06-13 (see Agent-Learnings.md). Always use
    rfind() so the splice happens at the file's ACTUAL closing </body>.

WHEN IT RUNS
    Wired into phase1c_content_drafter.sh — runs after render_content_html.py
    so the embedded lists always reflect what's actually been drafted.
"""

import json
import re
from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
META_DIR    = BASE_DIR / "outputs" / "meta-ads"
GADS_DIR    = BASE_DIR / "outputs" / "google-ads-rsa"
INDEX_PATH  = BASE_DIR / "docs" / "index.html"


def slugs_in(directory: Path) -> list[str]:
    if not directory.exists():
        return []
    return sorted(p.stem for p in directory.glob("*.md") if p.is_file())


def inject() -> None:
    meta_slugs = slugs_in(META_DIR)
    gads_slugs = slugs_in(GADS_DIR)

    html = INDEX_PATH.read_text(encoding="utf-8")
    new_block = (
        '<script id="paid-ad-list-block">\n'
        '// CB247 available Meta ad + Google RSA drafts — auto-generated by\n'
        '// scripts/inject_paid_ad_lists.py (runs from phase1c).\n'
        '// Brief renderer checks these lists before showing "View AI Draft".\n'
        f'window.AI_META_ADS    = {json.dumps(meta_slugs)};\n'
        f'window.AI_GOOGLE_RSAS = {json.dumps(gads_slugs)};\n'
        '</script>'
    )

    if 'id="paid-ad-list-block"' in html:
        updated = re.sub(
            r'<script id="paid-ad-list-block">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # CRITICAL: use rfind() to splice at the file's ACTUAL closing </body>.
        # The brief renderer JS includes a template literal containing </body>
        # mid-function — str.replace would corrupt it.
        idx = html.rfind("</body>")
        if idx >= 0:
            updated = html[:idx] + new_block + "\n" + html[idx:]
            action = "inserted (at rightmost </body>)"
        else:
            updated = html + "\n" + new_block
            action = "appended"

    if updated == html:
        print("[paid-ad-list] WARN — no change to docs/index.html")
        return

    INDEX_PATH.write_text(updated, encoding="utf-8")
    print(f"[paid-ad-list] OK — {action} · meta={len(meta_slugs)} · gads={len(gads_slugs)}")


if __name__ == "__main__":
    inject()
