"""
inject-promo-pipeline.py — Inject state/promo-pipeline.json into docs/index.html.

Same inline-injection pattern as inject-meta-ads.py + inject-social-block.py.
Reads state/promo-pipeline.json (written by scripts/work_queue/promo_concept_emitter.py)
and writes:
  <script id="promo-pipeline-block">window.PROMO_PIPELINE_LIVE = {...}</script>

The dashboard's _promoData() helper checks window.PROMO_PIPELINE_LIVE first
and falls back to the hardcoded PROMO_PIPELINE_DATA constant. Both
renderPromoPipeline() and renderAssetLibrary() consume the same source.

Run after promo_concept_emitter:
    ./.venv/bin/python3.13 scripts/work_queue/promo_concept_emitter.py
    ./.venv/bin/python3.13 scripts/inject-promo-pipeline.py
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
STATE_DIR = BASE_DIR / "state"
INDEX_PATH = BASE_DIR / "docs" / "index.html"
PROMO_FILE = STATE_DIR / "promo-pipeline.json"


def build_payload() -> dict | None:
    if not PROMO_FILE.exists():
        print(f"[promo-pipeline] {PROMO_FILE.relative_to(BASE_DIR)} missing — nothing to inject.")
        return None
    try:
        data = json.loads(PROMO_FILE.read_text())
    except Exception as e:
        print(f"[promo-pipeline] could not parse {PROMO_FILE}: {e}")
        return None
    return {
        "acquisition": data.get("acquisition", []),
        "retention":   data.get("retention", []),
        "generated_at": data.get("generated_at", datetime.now(timezone.utc).isoformat()),
        "generator":    data.get("generator", "promo_concept_emitter"),
    }


def main() -> int:
    payload = build_payload()
    if payload is None:
        return 0  # nothing to do, but not an error (file just missing)

    json_payload = json.dumps(payload, indent=2, default=str)
    new_block = (
        '<script id="promo-pipeline-block">\n'
        '// CB247 Promo Pipeline — live override for hardcoded PROMO_PIPELINE_DATA\n'
        '// Auto-generated by scripts/inject-promo-pipeline.py from state/promo-pipeline.json\n'
        f'window.PROMO_PIPELINE_LIVE = {json_payload};\n'
        '</script>'
    )

    if not INDEX_PATH.exists():
        print(f"[promo-pipeline] ERROR — {INDEX_PATH.relative_to(BASE_DIR)} missing.")
        return 1
    html = INDEX_PATH.read_text()

    if 'id="promo-pipeline-block"' in html:
        updated = re.sub(
            r'<script id="promo-pipeline-block">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # Insert just before window.DASHBOARD_DATA, matching sibling injectors
        anchor = 'window.DASHBOARD_DATA = {'
        idx = html.find(anchor)
        if idx == -1:
            updated = html.replace("</body>", new_block + "\n</body>")
        else:
            script_open = html.rfind("<script>", 0, idx)
            if script_open == -1:
                updated = html.replace("</body>", new_block + "\n</body>")
            else:
                updated = html[:script_open] + new_block + "\n" + html[script_open:]
        action = "inserted"

    if updated == html:
        print("[promo-pipeline] WARN — no change to index.html (regex didn't match? anchor missing?)")
        return 1

    INDEX_PATH.write_text(updated)
    n_acq = len(payload["acquisition"])
    n_ret = len(payload["retention"])
    print(f"[promo-pipeline] {action} block in docs/index.html "
          f"({n_acq} acquisition · {n_ret} retention concepts).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
