"""
inject-membership-data.py — Inject CB247 Membership Statistics block
into docs/index.html.

Same inline-injection pattern as inject-meta-ads.py.
Reads state/membership-data.json (produced by parse_membership_data.py)
and writes a <script id="membership-data-block">window.MEMBERSHIP_DATA = {...}
into docs/index.html.

Run after parse_membership_data.py:
  ./.venv/bin/python3.13 scripts/parse_membership_data.py
  ./.venv/bin/python3.13 scripts/inject-membership-data.py
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
STATE_DIR   = BASE_DIR / "state"
INDEX_PATH  = BASE_DIR / "docs" / "index.html"
DATA_FILE   = STATE_DIR / "membership-data.json"


def build_payload():
    if not DATA_FILE.exists():
        return None
    try:
        return json.loads(DATA_FILE.read_text())
    except Exception as e:
        print(f"[membership] could not parse {DATA_FILE}: {e}")
        return None


def inject():
    payload = build_payload()
    if payload is None:
        print("[membership] No membership data to inject. Run parse_membership_data.py first.")
        return

    json_payload = json.dumps(payload, indent=2, default=str)
    html = INDEX_PATH.read_text(encoding="utf-8")

    new_block = (
        '<script id="membership-data-block">\n'
        '// CB247 Membership stats — auto-generated by scripts/inject-membership-data.py\n'
        '// Source: state/membership-data.json (parsed from cb247-membership-inbox/*.xlsx)\n'
        f'window.MEMBERSHIP_DATA = {json_payload};\n'
        '</script>'
    )

    if 'id="membership-data-block"' in html:
        updated = re.sub(
            r'<script id="membership-data-block">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # Insert just before window.DASHBOARD_DATA — same pattern as sibling injectors
        anchor = 'window.DASHBOARD_DATA'
        idx = html.find(anchor)
        if idx == -1:
            updated = html.replace("</body>", new_block + "\n</body>")
        else:
            script_open = html.rfind("<script>", 0, idx)
            updated = html[:script_open] + new_block + "\n" + html[script_open:]
        action = "inserted"

    if updated == html:
        print("[membership] WARN — no change to index.html")
        return

    INDEX_PATH.write_text(updated, encoding="utf-8")
    period = ((payload.get("summary") or {}).get("period") or {}).get("raw") or "?"
    totals = (payload.get("summary") or {}).get("totals") or {}
    print(f"[membership] OK — block {action} in docs/index.html")
    print(f"           Week:   {period}")
    print(f"           Totals: New {totals.get('NewContracts',0)} · Ended {totals.get('EndedContracts',0)} · Future {totals.get('FutureCancellations',0)}")
    cw = payload.get("cleverwaiver") or {}
    if cw.get("available"):
        print(f"           Cleverwaiver: {cw.get('total_responses',0)} responses")


if __name__ == "__main__":
    inject()
