"""
inject-blog-drafts-index.py — Inject a list of available blog drafts into
docs/index.html so the dashboard can auto-attach drafts to content actions.

Scans docs/blog-drafts/*.html (top-level only, ignores subfolders for now)
and writes window.BLOG_DRAFTS_INDEX = {slug: url, ...} into docs/index.html
as a <script id="blog-drafts-index"> tag (same inject pattern as
inject-meta-ads.py, inject-promo-pipeline.py).

The dashboard's _findExistingDraft(action) helper then slug-matches a
content action's title against this index. e.g. "Improve organic content
for 'gym ellenbrook perth'" → slug 'gym-ellenbrook-perth' → matched.

Run after generate_briefs.py (which is itself wired into weekly-report.sh):
    .venv/bin/python3.13 scripts/inject-blog-drafts-index.py

USAGE: python scripts/inject-blog-drafts-index.py
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DRAFTS_DIR = BASE_DIR / "docs" / "blog-drafts"
INDEX_PATH = BASE_DIR / "docs" / "index.html"

# Drafts get served from GitHub Pages at this base
PUBLIC_BASE = "https://cb247agent.github.io/cb_claude/blog-drafts"


def build_payload() -> dict:
    if not DRAFTS_DIR.exists():
        print(f"[drafts-index] {DRAFTS_DIR.relative_to(BASE_DIR)} missing — empty index")
        return {}
    out: dict = {}
    for p in sorted(DRAFTS_DIR.glob("*.html")):
        slug = p.stem.lower()
        out[slug] = f"{PUBLIC_BASE}/{p.name}"
    return out


def main() -> int:
    payload = build_payload()
    if not INDEX_PATH.exists():
        print(f"[drafts-index] ERROR — {INDEX_PATH.relative_to(BASE_DIR)} missing.")
        return 1

    json_payload = json.dumps(payload, indent=2)
    new_block = (
        '<script id="blog-drafts-index">\n'
        '// CB247 Blog Drafts Index — available pre-written drafts in docs/blog-drafts/\n'
        '// Auto-generated by scripts/inject-blog-drafts-index.py\n'
        f'window.BLOG_DRAFTS_INDEX = {json_payload};\n'
        '</script>'
    )

    html = INDEX_PATH.read_text()

    if 'id="blog-drafts-index"' in html:
        updated = re.sub(
            r'<script id="blog-drafts-index">.*?</script>',
            lambda _: new_block,
            html,
            flags=re.DOTALL,
        )
        action = "replaced"
    else:
        # Insert just before window.DASHBOARD_DATA, matching sibling injectors
        anchor = "window.DASHBOARD_DATA = {"
        idx = html.find(anchor)
        if idx == -1:
            updated = html.replace("</body>", new_block + "\n</body>")
        else:
            script_open = html.rfind("<script>", 0, idx)
            if script_open == -1:
                updated = html.replace("</body>", new_block + "\n</body>")
            else:
                updated = html[:script_open] + new_block + "\n" + html[script_open:]
        action = "inserted"

    if updated == html:
        print("[drafts-index] WARN — no change to index.html")
        return 1

    INDEX_PATH.write_text(updated)
    print(f"[drafts-index] {action} block in docs/index.html ({len(payload)} drafts indexed).")
    for slug in payload:
        print(f"  · {slug}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
