"""
send_mwcc_management_report.py — Email the weekly MWCC management report.

Sends the HTML report generated by bake_mwcc_management_report.py as the
EMAIL BODY (inline HTML rendering) — not as an attachment — so management
can open and read it without downloading anything.

Recipients are determined by MWCC_MANAGEMENT_RECIPIENTS env var.
Falls back to WEEKLY_REPORT_RECIPIENT (Tia only) if MWCC_MANAGEMENT_RECIPIENTS
is not set — this is the safe default during testing.

Env vars expected:
    SMTP_HOST                       (e.g. smtp.gmail.com)
    SMTP_PORT                       (default 587)
    SMTP_USER                       (sender email)
    SMTP_PASS                       (app password)
    MWCC_MANAGEMENT_RECIPIENTS      (comma-separated emails — preferred)
    WEEKLY_REPORT_RECIPIENT         (fallback — single email, Tia)

Wired into: scripts/weekly-report-mwcc.sh AFTER bake_mwcc_management_report.py.

Cadence: Monday 14:00 AWST (after the MWCC pipeline completes).
"""

from __future__ import annotations

import datetime as _dt
import os
import smtplib
import sys
from email.message import EmailMessage
from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = BASE_DIR / "outputs" / "mwcc"


def _load_dotenv():
    """Best-effort .env loader (no third-party dep)."""
    env = BASE_DIR / ".env"
    if not env.exists():
        return
    for line in env.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


def _recipients() -> list[str]:
    """Resolve recipient list with safe fallback to Tia-only."""
    raw = os.getenv("MWCC_MANAGEMENT_RECIPIENTS", "").strip()
    if raw:
        addrs = [e.strip() for e in raw.split(",") if e.strip()]
        if addrs:
            return addrs
    fb = os.getenv("WEEKLY_REPORT_RECIPIENT", "").strip()
    if fb:
        print(f"[mwcc-mgmt-email] MWCC_MANAGEMENT_RECIPIENTS not set — falling back to {fb}")
        return [fb]
    print("[mwcc-mgmt-email] No recipients configured. Set MWCC_MANAGEMENT_RECIPIENTS in .env.")
    return []


def _find_latest_report() -> Path | None:
    today = _dt.date.today().strftime("%Y-%m-%d")
    candidate = OUTPUTS_DIR / f"management-report-{today}.html"
    if candidate.exists():
        return candidate
    # Fallback: most recent any-date
    reports = sorted(OUTPUTS_DIR.glob("management-report-*.html"), reverse=True)
    return reports[0] if reports else None


def main() -> int:
    _load_dotenv()

    report = _find_latest_report()
    if not report:
        print("[mwcc-mgmt-email] No management-report-*.html found in outputs/mwcc/ — run bake first.")
        return 1

    recipients = _recipients()
    if not recipients:
        return 0  # graceful exit — pipeline keeps moving

    host = os.getenv("SMTP_HOST")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER")
    pwd  = os.getenv("SMTP_PASS")
    if not all([host, user, pwd]):
        print("[mwcc-mgmt-email] SMTP_HOST/USER/PASS missing in .env — skipping send")
        return 0

    html_body = report.read_text(encoding="utf-8")

    # Build subject from the report date
    today_str = _dt.date.today().strftime("%a %d %b %Y")
    subject = f"MWCC Management Report — {today_str}"

    msg = EmailMessage()
    msg["From"]    = user
    msg["To"]      = ", ".join(recipients)
    msg["Subject"] = subject
    # Plain-text fallback for clients that block HTML
    msg.set_content(
        f"MWCC Management Report — {today_str}\n\n"
        f"This week's report is available as an HTML email below.\n"
        f"If your client blocks HTML, the same report is saved at:\n"
        f"  {report.relative_to(BASE_DIR)}\n\n"
        f"— MWCC Marketing Ops"
    )
    msg.add_alternative(html_body, subtype="html")

    print(f"[mwcc-mgmt-email] Sending '{subject}' to {len(recipients)} recipient(s)")
    for r in recipients:
        print(f"  → {r}")

    try:
        with smtplib.SMTP(host, port, timeout=30) as s:
            s.starttls()
            s.login(user, pwd)
            s.send_message(msg)
        print(f"[mwcc-mgmt-email] ✅ Sent")
        return 0
    except Exception as e:
        print(f"[mwcc-mgmt-email] ⚠️  Send failed: {e}")
        return 0  # non-fatal — pipeline keeps moving


if __name__ == "__main__":
    sys.exit(main())
